image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.11

environment:
  GITHUB_TOKEN:
    secure: nJq0vhcsoxHg/XfqreXfulghToF4PAuTmSAXnuCx980Gz8BbY4msEgnYPho1c3+8qRPfC2grDbdmDEE9SdKVr5k9LC9mRhn9w3jUK3o7QapSl8vXwVD8+zXf9DstJUvm

install:
- pip install -r requirements.txt


test: off

# Publish artifacts to GitHub Releases on "tag" builds --icon dataicon.png 
deploy:
  release: DataMasking-v$(APPVEYOR_BUILD_VERSION)
  description: 'DataMasking Tool for ETL'
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    branch: main
    APPVEYOR_REPO_TAG_MAIN: true
    APPVEYOR_REPO_TAG: trues


#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a DataMasking-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: DataMasking-windows.zip
 
  build_script:
  - flet pack main.py --name DataMasking --add-data "assets;assets" --product-name DataMasking --product-version "0.0.1" --copyright "Copyright (c) 2023 GKTwin Apps"

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf DataMasking-macos.tar.gz -C dist DataMasking.app

  artifacts:
  - path: DataMasking-macos.tar.gz

  build_script:
  - flet pack main.py --name DataMasking --add-data "assets:assets" --product-name DataMasking --product-version "0.0.1" --copyright "Copyright (c) 2023 GKTwin Apps"

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf DataMasking-linux.tar.gz -C dist DataMasking

  artifacts:
  - path: DataMasking-linux.tar.gz

  build_script:
  - flet pack main.py --name DataMasking --add-data "assets:assets" --product-name DataMasking --product-version "0.0.1" --copyright "Copyright (c) 2023 GKTwin Apps"
